# NAME: Stewart Dulaney,Pariya Samandi
# EMAIL: sdulaney@ucla.edu,pari.samandi@gmail.com
# ID: 904-064-791,205-092-357

#!/usr/bin/env python3

import sys, string, locale

def init_lists():
    ....
def block_errors(out_file):
    ....
def duplicate_allocated_blocks(out_file):
    ...

def unallocated_inode(directory_file, out_file):
    ...
def missing_inode(inode_file, out_file):
    ...
def incorrect_link_count(inode_file, out_file):
    ...
def incorrect_directory_entry(directory_file, out_file):
    ...
def open_files():
    ...
def close_files():
    ...
def main():
    ...
    